name: Continuous Integration (CI) of Sputnik
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile:
    name: Compile Sputnik
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle
      
      - name: Compile project
        run: |
          ./gradlew clean compileJava
  
      - name: Test project
        run: |
          ./gradlew clean test --info
  test:
    name: Test Sputnik
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle
  
      - name: Test project
        run: |
          ./gradlew clean test --info
